# Generated by Django 3.2.4 on 2021-07-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210627_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
