# Generated by Django 3.2.4 on 2021-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
