# Generated by Django 3.2.4 on 2021-07-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210705_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Dispatched', 'Dispatched')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
